nodeLinker: node-modules

npmAuthToken: "${GITHUB_OAUTH_TOKEN}"

npmPublishRegistry: "https://registry.npmjs.org"
npmPublishAccess: public

npmScopes:
  rvoh:
    npmAlwaysAuth: true
    npmRegistryServer: "https://registry.npmjs.org"
