nodeLinker: node-modules

npmScopes:
  rvohealth:
    npmAuthToken: '${GITHUB_OAUTH_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'
  # taskforcesh:
  #   npmAlwaysAuth: true
  #   npmAuthToken: '${BULLMQ_PRO_NPM_TOKEN}'
  #   npmRegistryServer: 'https://npm.taskforce.sh/'
  #
