nodeLinker: node-modules

npmAuthToken: "${GITHUB_OAUTH_TOKEN}"

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmScopes:
  rvoh:
    npmAlwaysAuth: true
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
