apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: psychic-workers
  description: A background job queue-worker system built for psychic applications
spec:
  type: library # can be one of: service, library, website, event-driven-service
  lifecycle: production # can be one of: experimental, production, deprecated
  owner: team-wellos-be
