const assert = require('node:assert/strict')
const { BaseScheduledService, background } = require('@rvoh/psychic-workers')
const { DuplicateNamedWorkstream, InvalidJobSchedulerLocator } = require('@rvoh/psychic-workers/errors')
const schedulerTypes = require('@rvoh/psychic-workers/types')

assert.equal(typeof BaseScheduledService.jobSchedulerLocator, 'function')
assert.equal(typeof BaseScheduledService.unschedule, 'function')
assert.equal(typeof background.getJobSchedulers, 'function')
assert.equal(typeof background.removeJobScheduler, 'function')
assert.equal(typeof InvalidJobSchedulerLocator, 'function')
assert.equal(typeof DuplicateNamedWorkstream, 'function')
assert.equal(typeof schedulerTypes, 'object')
